### ISSUE TITLE
我们正在建立粉丝群

### ISSUE THREAD

**Issue by dapang518518** [filecoin-vision/manifesto#1]
我的微信dapang5185

**Comment by dapang518518** [comment]
我们正在建立filecoin visoin 粉丝群，感兴趣的可以加我，备注filecoinvision

**Comment by ljp1373** [comment]
大胖牛逼！

**Comment by jzyfiv** [comment]
雷同的issue先关闭

**Comment by dapang518518** [comment]
我看已经被被关了，你如果想保持匿名可以只使用电报，我搞了一个微信群。



---原始邮件---
发件人: "jzyfiv"<notifications@github.com&gt;
发送时间: 2020年9月18日(周五) 中午11:45
收件人: "filecoin-vision/manifesto"<manifesto@noreply.github.com&gt;;
抄送: "dapang518518"<906307509@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [filecoin-vision/manifesto] 我们正在建立粉丝群 (#1)




 
雷同的issue先关闭
